//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Address
{
	public virtual string line1
	{
		get;
		set;
	}

	public virtual List <Person> residents
	{
		get;
		set;
	}

	public virtual IEnumerable<Person> Person
	{
		get;
		set;
	}

}

